#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -eu

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
#
allownonascii=$(git config --type=bool hooks.allownonascii || true) # Slight modification of the template (adding `|| true`) so script doesn't immediately fail under `set -e`.

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# MAIN ADDITION:

echo 'FIXME: This hook currently only examines the working tree for my purposes, not staged data.'

# Note that this is hardcoded to look at `${HOME}`, not wherever this repo is "checked-out", because this is a bare git repo.
# Thankfully this is for my dotfiles, so they better be in ${HOME}!
if ! diff <(sed -n '/^# Should be alpha/, $p' "${HOME}/.gitignore" | grep --invert-match '^#') <(sed -n '/^# Should be alpha/, $p' "${HOME}/.gitignore" | grep --invert-match '^#' | sort); then
    echo 'Alphabetize the items at the end of  `~/.gitignore` according to the output of diff printed above.'
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
